/**:
  ros__parameters:
    image_transport: "raw"
    family: "36h11"
    size: 0.1

    # 태그 0번부터 9번까지 10개 한 번에 등록 (크기는 모두 0.1m)
    tag:
      ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      frames: ["tag_0", "tag_1", "tag_2", "tag_3", "tag_4", "tag_5", "tag_6", "tag_7", "tag_8", "tag_9"]
      sizes: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]